### PR TITLE
fix: required fields validation

### PR DESCRIPTION
**Pull request by krasimirkolev**

### CODE REVIEW

**Review by zetxx — APPROVED** [review]

**Comment by stambata** [comment]
Can you give more details about what case this change fixes?
according to json schema spec: https://json-schema.org/understanding-json-schema/reference/object.html#required-properties
schema.required is a valid configuration for objects only.
That's why it was polyfilled for simple types:
https://github.com/softwaregroup-bg/ut-swagger2-validator/blob/master/validator.js#L10

where if schema.required is boolean it gets deleted and substituted with custom keyword 'x-required'

**Comment by stambata** [comment]
I am not saying it is wrong but the way it was changed will probably break something else.
An example would be very helpful

**Comment by zetxx** [comment]
just there is no `x-required` property in schema object, but there is `required` property

**Comment by stambata** [comment]
please read my comment

**Comment by zetxx** [comment]
so, how i can tell that the property is required ? when it is coming from formData?
also you will newer have x-required property in validator.js:137 , for it to persist there, someone should change schema object either by reference, or trough transformation.

**Pull request merged**
